### ISSUE TITLE
Versioning?

### ISSUE THREAD

**Issue by brokenpip3** [checkpoint-restore/checkpointctl#34]
Hi there,

I would like to create an aur package (arch linux users repo) for checkpointctl but I saw that there is no version at all or any git tag.
May I ask why?
Do you have in plan to release any version soon?
I can create the package from the latest git commit but it's better to a versioning.

thanks

**Comment by adrianreber** [comment]
There is no version, yet, because I didn't want to commit to an API. To not have to deal with GO's requirements when it comes to package versioning, I just left it without.

We are using it in CRI-O and Podman and to be able to easily change the API there is no version.

We can add something like 0.1.0 if it would help you. Once the API seems settled there will be a version.

**Comment by brokenpip3** [comment]
> There is no version, yet, because I didn't want to commit to an API. To not have to deal with GO's requirements when it comes to package versioning, I just left it without.
> 
> We are using it in CRI-O and Podman and to be able to easily change the API there is no version.

Make sense, ty for the explanation :) 

> 
> We can add something like 0.1.0 if it would help you. Once the API seems settled there will be a version.

No it's better like this otherwise the package will remain not-updated until the api. I'm going to create a `git` package and once a versioning will become a thing here I will create another package that will follow the versioning.

Thanks!

**Comment by brokenpip3** [comment]
fyi: this is the package: https://aur.archlinux.org/packages/checkpointctl-git

**Comment by adrianreber** [comment]
We just tagged a v0.1.0 release.

**Comment by brokenpip3** [comment]
Great! will create another package :)
